[package]
name = "ping-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ctrlc = { version = "3.0", features = ["termination"] }
dns-lookup = "1.0.8"
winping = "0.10.1"